<?php

// @FIXME: this should be done via variable or a more reliable way. not just being hardcoded.
define('collabco_PROFILE_PHOTO_FIELD', 'field_profile_photo');

function collabco_profile_form_user_register_form_alter(&$form, &$form_state) {
  // Make the default photo profile hidden if it's already there.
  if (isset($form['picture'])) {
    $form['picture']['#access'] = false;
  }
}

function collabco_profile_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  // Make the default photo profile hidden if it's already there.
  if (isset($form['picture'])) {
    $form['picture']['#access'] = false;
  }
  // We are going to do the submit process after everything has done
  $form['#submit'][] = '_collabco_profile_form_submit';
}

function _collabco_profile_clean_pass_reset_form(&$form) {
  foreach ($form as $key=>&$item) {
    if ($key != 'actions' and $key != 'account') {
      if (strpos($key, '#') === false and is_array($item)) {
        $item['#access'] = false;
      }
    }
  }
  foreach ($form['account'] as $key=>&$item) {
    if (!in_array($key, array('pass', 'current_pass_required_values'))) {
      if (strpos($key, '#') === false and is_array($item)) {
        $item['#access'] = false;
      }
    }
  }
}

function _collabco_profile_form_submit($form, &$form_state) {

    if (isset($form_state['values']['profile_profile'][collabco_PROFILE_PHOTO_FIELD])) {

      // let's get the file id which has just updated
      $fid = $form_state['values']['profile_profile'][collabco_PROFILE_PHOTO_FIELD]['und'][0]['fid'];

      // get the user which is running the form
      $uid = $form['#user']->uid;

      _collabco_profile_update_user_photo($uid, $fid);

    }
}



/**
 * Implements hook_comment_insert().
 */
function collabco_profile_comment_insert($comment) {

  // Integration with collabco_email
  if (module_exists('collabco_email')) {
    collabco_email_callback_comment_added($comment);
  }
  
}




/**
 * Updates the profile photo based on an already-updaloaded drupal file
 * @TODO: more check and validation.
*/
function _collabco_profile_update_user_photo($uid, $fid) {

  $user = user_load($uid);
  $file = file_load($fid);
  $picture = (object) array(
    'fid' => $file->fid
    , 'uid' => $uid
    , 'filename' => $file->filename
    , 'filemime' => $file->filemime
    , 'uri' => $file->uri
  );
  $user->picture = $picture;
  user_save($user);
}


