<?php



/**
 * Implementation of hook_og_membership_update()
 * Just for backward compatibility.
 * @TODO should be removed for a fresh product.
 */
function meta_group_og_membership_update(OgMembership $og_membership) {
	_meta_group_og_membership_update($og_membership);
}

/**
 * Implementation of hook_og_membership_insert()
 * 
 */
function meta_group_og_membership_insert(OgMembership $og_membership) {
	_meta_group_og_membership_update($og_membership);
}

function _meta_group_og_membership_update(OgMembership $og_membership) {
	$gid = $og_membership->gid;
	$uid = $og_membership->etid;
	$node = node_load($gid);
	if ($node->uid == $uid) {
		_meta_group_role_admin_grant($gid, $uid);
	}
}

function _meta_group_role_admin_grant($gid, $uid) {
	$rid = _meta_group_get_rid_by_role_name($gid, OG_ADMINISTRATOR_ROLE);
	og_role_grant('node', $gid, $uid, $rid);
}

/**
 * Implementation of hook_theme_registry_alter()
 */
function meta_group_theme_registry_alter(&$theme_registry) {
	$path = drupal_get_path('module', 'meta_group') . '/templates';
	// add templates directory to Drupal default directories
	$theme_registry += drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
}



/**
 * Implements hook_views_api().
 */
function meta_group_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'meta_group') . '/includes/views',
  );
}

function meta_group_og_user_access_alter(&$permissions, $context) {
	if ($context['group_type'] == 'node') {
		$node = $context['group'];
		$group_is_close = _meta_group_is_close($node);

		$permissions['subscribe'] = true;
		$permissions['subscribe without approval'] = ($group_is_close == false);
	}
}

function _meta_group_is_close($node) {
	$wrapper = entity_metadata_wrapper('node', $node);
	if (!isset($wrapper->{META_OG_ACCESS_FIELD})) {
		return false;
	}
	return $wrapper->{META_OG_ACCESS_FIELD}->value() == META_OG_ACCESS_CLOSE;
}

function meta_group_menu() {
	$items = array();

	$items['profile/hubs'] = array(
	    'title' => 'Your Hubs',
	    'description' => 'Hubs you have hosted or joined',
	    'page callback' => '_meta_group_page_profile_hubs',
	    'access callback' => true,
	);

	$items['node/%node/topics'] = array(
	    'title' => 'Topics',
	    'description' => 'Topics within this hub',
	    'page callback' => '_meta_group_page_topics',
	    'page arguments' => array(1),
	    'access callback' => true,
	);
	$items['node/%node/library'] = array(
	    'title' => 'Library',
	    'description' => 'Library of this hub',
	    'page callback' => '_meta_group_page_library',
	    'page arguments' => array(1),
	    'access callback' => true,
	);
	$items['node/%node/members'] = array(
	    'title' => 'Members',
	    'description' => 'This Hub\'s members',
	    'page callback' => '_meta_group_page_members',
	    'page arguments' => array(1),
	    'access callback' => true,
	);
	$items['node/%node/add/member'] = array(
	    'title' => 'Add a member',
	    'description' => '',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('meta_group_add_user_form', 1),
	    'access callback' => 'meta_group_add_user_access',
	    'access arguments' => array(1),
	);
	$items['node/%node/add/member/co-owner'] = array(
	    'title' => 'Add a co-owner',
	    'description' => '',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('meta_group_add_user_form', 1, 'co-owner'),
	    'access callback' => 'meta_group_add_user_access',
	    'access arguments' => array(1, 'co-owner'),
	);
	return $items;
}


function meta_group_add_user_access($node, $type='member') {
	if (!og_is_group('node', $node)) {
		return false;
	}
	$gid = $node->nid;
	global $user;
	$is_group_admin = og_user_access('node', $gid, 'administer group');
	if (user_access('administer group')) {
		return true;
	}
	if ($type == 'member' and og_user_access('node', $gid, 'add user')) {
		return true;
	}
	if ($type == 'co-owner' and meta_og_state_is_draft($gid) and meta_group_is_owner($gid)) {
		return true;
	}
	return false;
}

function _meta_group_page_profile_hubs() {
	$groups_hosted = views_embed_view('meta_membership_list_group_by_user', 'owned');
	$groups_joined = views_embed_view('meta_membership_list_group_by_user', 'list');
	
	$content = t('<h2>Hubs You Hosted</h2> !groups_hosted <h2>Hubs You Joined</h2> !groups_joined', array(
		'!groups_hosted' => $groups_hosted
		, '!groups_joined' => $groups_joined
	));
	return $content;
}

function _meta_group_page_topics($node) {
	return views_embed_view('join_the_conversation', 'topics_of_hub', $node->nid);
}

function _meta_group_page_library($node) {
	 return views_embed_view('recent_files', 'library_in_hub', $node->nid);
}

function _meta_group_page_members($node) {
	 return views_embed_view('meta_user_list_by_group', 'members_all', $node->nid);
}

function meta_group_theme($existing, $type, $theme, $path)
{
  return array(
      'group_actions_template' => array(
        'template' => 'group-actions-template',
        'variables' => array(
        	'gid' => 0
        )
     ),
  ); 
}

/**
 * Implements hook_block_info().
 *
 */
function meta_group_block_info() {
	$blocks = array();
	$blocks['group_actions'] = array(
		'info' => t('Actions for a specific Group')
		, 'cache' => DRUPAL_NO_CACHE,
	);
	return $blocks;
}


/**
 * Implements hook_block_view().
 *
 */
function meta_group_block_view($delta = '') {
	switch ($delta) {
		case 'group_actions':
			$node = menu_get_object();
			if (!isset($node->nid)) {
				return;
			}
			if (!og_is_group('node', $node->nid)) {
				return;
			}
			$gid = $node->nid;
			$block['subject'] = NULL;
			$content = theme('group_actions_template', array('gid' => $gid));
			
			//$content .= _meta_group_block_actions($gid);

			$block['content'] = $content;
		break;
	}
	return $block;
}


function meta_group_preprocess_group_actions_template(&$variables) {
	
	$gid = $variables['gid'];
	$links = array();

	$is_admin = user_access('administer group') || og_user_access('node', $gid, 'administer group');

	$is_owner = meta_group_is_owner($gid);


    if ($is_owner and meta_og_state_is_draft($gid)) {
    	$links[] = array(
    		'href' => sprintf('group/node/%d/send-for-revision', $gid)
    		, 'title' => 'Send for revision'
    		, 'icon' => 'upload'
    		, 'classes' => array()
    	);
    }

	// ** Edit the group
	// If:
	//	- The user has general 'administer groups' permission
	//  - Or the user is the owner and the hub is still in draft
	// 
    if (user_access('administer group') or ($is_owner and meta_og_state_is_draft($gid))) {
    	$links[] = array(
    		'href' => sprintf('node/%d/edit', $gid)
    		, 'title' => 'Edit the Hub'
    		, 'icon' => 'edit'
    		, 'classes' => array()
    	);
    }
	// ** Add more co-owner
	// If:
	//	- user has 'administer group' permission ('administrator role' of the group or the Content Manager with that permission)
	// 
	if (user_access('administer group') or ($is_owner and meta_og_state_is_draft($gid))) {
    	$links[] = array(
    		'href' => sprintf('node/%s/add/member/co-owner', $gid)
    		, 'title' => 'Add a co-owner'
    		, 'icon' => 'cog'
    	);
	}

	// ** Add a member
	// If:
	//	- user has 'add user' permission (should have been set for members)
	//  
	if ($is_admin or og_user_access('node', $gid, 'add user')) {
    	$links[] = array(
    		'href' => sprintf('node/%s/add/member', $gid)
    		, 'title' => 'Add a member'
    		, 'icon' => 'user'
    		, 'classes' => array('btn-success')
    	);
	}

	// ** Subscribe to group
	// If:
	//	- user is not a member
	//  
	if (!og_is_member('node', $gid)) {
    	$links[] = array(
    		'href' => sprintf('group/node/%s/subscribe', $gid)
    		, 'title' => 'Join this hub'
    		, 'icon' => 'plus'
    		, 'classes' => array('btn-success')
    	);
	}


	// ** Leave the group
	// If:
	//	- user is already a member
	//  
	if (!$is_owner and og_is_member('node', $gid)) {   
    	$links[] = array(
    		'href' => sprintf('group/node/%s/unsubscribe', $gid)
    		, 'title' => 'Unsubscribe from this Hub'
    		, 'icon' => 'remove'
    		, 'classes' => array('btn-danger')
    	);
	}

	$variables['links'] = $links;

}
/**
 * $type: can be 'co-owner' or ''
 *
 */
function meta_group_add_user_form($form, &$form_state, $node, $type='') {
	module_load_include('inc', 'og_ui', 'og_ui.admin');
	$form = og_ui_add_users($form, $form_state, 'node', $node->nid);
	$form['og_user']['roles']['#access'] = false;
	$form['membership_fields']['og_membership_request']['#access'] = false;
	$meta_roles = array();
	foreach ($form['og_user']['roles']['#options'] as $rid => $role_name) {
		if ($type == 'co-owner' and $role_name == OG_ADMINISTRATOR_ROLE) {
			$meta_roles[] = $rid;
		}
	}
	$form_state['meta_roles'] = $meta_roles;
	return $form;
}


/**
 * Validate handler; Add users to group.
 */
function meta_group_add_user_form_validate($form, &$form_state) {
	og_ui_add_users_validate($form, $form_state);
}


/**
 * Submit handler; Add users to group.
 */
function meta_group_add_user_form_submit($form, &$form_state) {
	foreach ($form_state['meta_roles'] as $role) {
		$form_state['values']['roles'][$role] = $role;
	}
	og_ui_add_users_submit($form, $form_state);
}




/**
 * Helper functions
 */

/**
 * @return TRUE if the user is the owner
 */
function meta_group_is_owner($gid, $uid=NULL) {
  global $user;
  if (!og_is_group('node', $gid)) {
    return false;
  }
  if (!isset($uid)) {
  	$uid = $user->uid;
  }
  $node = node_load($gid);
  return ($uid == $node->uid);
}

/**
 * @return TRUE if the user is the owner or co-owner
 */
function meta_group_is_coowner($gid, $uid=NULL) {
	// @FIXME: implement the functionality
	global $user;
	if (isset($uid)) {
		$account = user_load($uid);
	} else {
		$account = $user;
	}
	return og_user_access('node', $gid, 'administer group', $account);
}

/**
 * @param $gid Gr
 *	Group id
 * @param $role_name
 * The role name; you could also use standard OG role names:
 * - OG_ADMINISTRATOR_ROLE
 * - OG_AUTHENTICATED_ROLE
 * - OG_ANONYMOUS_ROLE
 *
 * @return role id for a specified role 
 */
function _meta_group_get_rid_by_role_name($gid, $role_name) {
	$node = node_load($gid);
	$roles = og_roles('node', $node->type, $gid);
	foreach ($roles as $_rid=>$_rname) {
		if ($_rname == $role_name) {
			return $_rid;
		}
	}
	return;
}


