<?php

/**
 * @file
 * collabco_views.module
 * Adds complex fields, filters and sorts to easily build Views member reports.
 */

/**
 * Implements hook_views_api().
 */
function collabco_views_views_api() {
  return array(
    'api' => views_api_version(),
    'path' => drupal_get_path('module', 'collabco_views') . '/views',
  );
}

/**
 * Implements hook_preprocess_date_views_pager().
 */
function collabco_views_preprocess_date_views_pager(&$vars) {
  // This hook was implemented to work around a bug in the Date module that
  // caused the wrong date format to be shown on monthly calendars.
  // However, using the latest version of Date 7.x-2.x-dev (7.x-2.9 when
  // officially released), this hook implementation is no longer required.
}