<?php

/**
 * @file meta_user_settings.module
 * The main file for the module containing hooks and helper functions.
 */

function meta_user_settings_defaults() {
	return array(
		'group_hostedby__member_join' => true
		, 'group_hostedby__topic_added' => true
		, 'group_hostedby__library_added' => true
		, 'group_memberof__member_join' => true
		, 'group_memberof__topic_added' => true
		, 'group_memberof__library_added' => true

		, 'topic_hostedby__comment_replied' => true
		, 'topic_hostedby__comment_added' => true
		, 'topic_followedby__comment_replied' => true
		, 'topic_followedby__comment_added' => true
	);
}

function meta_user_settings_get($key=null, $account=null) {
	if (!isset($account)) {
		global $user;
		$account = user_load($user->uid);
	}
	$data = $account->data['meta_user_settings'];
	if (!isset($key)) {
		return $data;
	}
	if (isset($data[$key])) {
		return $data[$key];
	}
	$defaults = meta_user_settings_defaults();
	if (isset($defaults[$key])) {
		return $defaults[$key];
	}
	return null;
}

/**
 * Implements hook_form_alter().
 */
function meta_user_settings_form_alter(&$form, &$form_state, $form_id) {
	if (!in_array($form_id, array('user_register_form', 'user_profile_form'))) {
		return;
	}
	if ($form['#user_category'] != 'account') {
		return;
	}
    $account = $form['#user'];
	$form['meta_user_settings'] = array(
		'#type' => 'fieldset',
		'#title' => t('Notification settings'),
		'#weight' => 1,
		'#collapsible' => true,
		'#access' => true,
	);

	$config = array(
		'topic_hostedby' => t('For Topics I host, email me when')
		, 'topic_followedby' => t('For Topics I follow, email me when')
	);
	foreach ($config as $config_key=>$label) {
		$keys = array(
			$config_key . '__' . 'comment_replied' => t('Someone replies to my comment')
			, $config_key . '__' .'comment_added' => t('New comments are added')
		);
		$values = array();
		foreach ($keys as $_key=>$_title) {
			if (meta_user_settings_get($_key)) {
				$values[$_key] = $_key;
			}
		}
		$form['meta_user_settings']['meta_user_settings_' . $config_key] = array(
			'#type' => 'checkboxes'
			, '#title' => $label
			, '#default_value' => $values
			, '#options' => $keys
			, '#access' => true
		);
	}


	$config = array(
		'group_hostedby' => t('For group I host, email me when')
		, 'group_memberof' => t('For group I belong to, email me when')
	);
	foreach ($config as $config_key=>$label) {
		$keys = array(
			$config_key . '__' . 'member_join' => t('A new member joins')
			, $config_key . '__' .'topic_added' => t('A topic is added')
			, $config_key . '__' . 'library_added' => t('A library file is added')
		);
		$values = array();
		foreach ($keys as $_key=>$_title) {
			if (meta_user_settings_get($_key)) {
				$values[$_key] = $_key;
			}
		}
		$form['meta_user_settings']['meta_user_settings_' . $config_key] = array(
			'#type' => 'checkboxes'
			, '#title' => $label
			, '#default_value' => $values
			, '#options' => $keys
			, '#access' => true
		);
	}
}


/**
 * Implements hook_user_presave().
 */
function meta_user_settings_user_presave(&$edit, $account, $category) {
	$data = array();
	$config_keys = array(
		'group_hostedby'
		, 'group_memberof'
		, 'topic_hostedby'
		, 'topic_followedby'
	);
	foreach ($config_keys as $config_key) {
		$data = array_merge($data, $edit['meta_user_settings_' . $config_key]);
	}
	$edit['data']['meta_user_settings'] = $data;
}










