<?php


/*
 * Implements hook_form_alter()
 */
function meta_ux_form_alter(&$form, &$form_state) {
  
}

function meta_ux_form_node_form_alter(&$form, &$form_state) {
  $node = $form_state['node'];
  if (!isset($node->nid) || isset($node->is_new)) {
      $node_type = $node->type;
      if ($node_type == 'conversation') {
        unset($form['body']['und'][0]['summary']['#access']);
        //$form['flag']['follow']['#default_value'] = 1;
        $form['flag']['#access'] = false;
      }
  }
}

function meta_ux_preprocess_page(&$vars) {
  $menu = menu_get_item();
  $path = $menu['path'];

  global $user;
  if (empty($user->uid)) {
    $vars['theme_hook_suggestions'][] = 'page__annon';
    _meta_ux_prepare_vars_annon($vars);
  }

  // Change the page title.
  if ($path == 'user/%/edit') {
    drupal_set_title('Edit your account');
  }
  if ($path == 'user/%/edit/profile') {
    drupal_set_title('Edit your profile');
  }

  if ($path == 'user/%') {
    drupal_set_title('');
  }
}



function meta_ux_form_user_register_form_alter(&$form, &$form_state) {
  $email_desc = array(
    '#markup' => '<div class="ui-box">

      <p>
          Users with approved email addresses will enter the site immediately. Please use the email you supplied to META when you applied for membership (This is probably your corporate email address).
      </p>

      <p>
          If you are not pre-approved, you may need to wait 24 hours for administrator approval. Contact contact@meta.gov.au with any questions.
      </p>

    </div>'
    );
  $account = array_reverse($form['account'], true);
  $account['description'] = $email_desc;
  $form['account'] = array_reverse($account, true);
  $form['account']['mail']['#description'] = t('Must be a valid email address, we will send you a message with a link to activate your account.');
}

function meta_ux_form_user_login_alter(&$form, &$form_state, $form_id) {
  $form['name']['#title'] = t('Username / email');
  $form['name']['#description'] = t('Log in with either your assigned username or your e-mail address.');

  $form['pass']['#title'] = $form['pass']['#title'] . l('Forgotten your password?', 'user/password');
  unset($form['pass']['#description']);
  $singup_link = t('<h3>Don\'t have an account yet? </h3>
  <div class="row-fluid">
      <div class="span6">
      <p>Meta members:</p> 
        !singup_link
      </div>
      <div class="span6">
      <p>Don\'t belong to Meta?</p>
        !membership_link
      </div>
  </div>', array(
    '!singup_link' => l('Register now', 'user/register')
    , '!membership_link' => l('Become a member', 'http://meta.org.au/membership/')));

  $form['actions'][] = array('#markup' => $singup_link);

}

function _meta_ux_prepare_vars_annon(&$vars) {
    if ($_GET['q'] == 'user/register') {
      $vars['title'] = t('Create a new account');
      $vars['subtitle'] = t('Register now for the meta members only');
    }
    if ($_GET['q'] == 'user') {
      $vars['title'] = t('Members log in');
      $vars['subtitle'] = t('Secure members-only area');
    }
}




