<?php

/**
 * Implements hook_preprocess_html()
 */
function collabco_ux_preprocess_html(&$vars) {
  $menu = menu_get_item();
  $path = $menu['path'];
  if (_collabco_ux_path_is_login_forms($path)) {
    $vars['classes_array'][] = 'ui-login-forms';
  }
}

/**
 * Implements hook_preprocess_page()
 */
function collabco_ux_preprocess_page(&$vars) {
  $menu = menu_get_item();
  $path = $menu['path'];
  if (_collabco_ux_path_is_login_forms($path)) {
    $vars['theme_hook_suggestions'][] = 'page__login_forms';
    if ($path == 'user/register') {
      $vars['title'] = t('Create a new account');
      $vars['subtitle'] = t('Register now for the collabco members only');
    }
    if ($path == 'user' or $path == 'user/login') {
      $vars['title'] = t('Member log in');
      $vars['subtitle'] = t('Secure members-only area');
    }
    if ($path == 'user/password') {
      $vars['title'] = t('Password recovery');
      $vars['subtitle'] = t('');
    }
    // Change the page title.
    if ($path == 'user/%/edit') {
      drupal_set_title('Edit your account');
    }
    if ($path == 'user/%/edit/profile') {
      drupal_set_title('Edit your profile');
    }
    if ($path == 'user/%') {
      drupal_set_title('');
    }
  }
}

function _collabco_ux_path_is_login_forms($path) {
  $menu = menu_get_item();
  $path = $menu['path'];
  if (in_array($path, array('user/register', 'user/login', 'user/password'))) {
    return true;
  }
  global $user;
  if (empty($user->uid) and $path == 'user') {
    return true;
  }
  if (_collabco_ux_path_is_reset_password($user)) {
    return true;
  }
  return false;
}

function _collabco_ux_path_is_reset_password($account=null) {
  global $user;
  if (isset($account)) {
    $account = user_load($user->uid);
  }
  return isset($_SESSION['pass_reset_' . $account->uid]) && isset($_GET['pass-reset-token']) && ($_GET['pass-reset-token'] == $_SESSION['pass_reset_' . $account->uid]);
}


