<?php



/**
 * Implements hook_block_info().
 */
function iin_navigation_block_block_info() {
  $blocks = array();
  $blocks['iin_navigation_block'] = array(
    'info' => t('IIN Navigtation Block'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function iin_navigation_block_block_view($delta='') {
  $block = array();
  global $base_url;
  switch($delta) {
    case 'iin_navigation_block' :
   // $block['content'] = '<div id="iin-logo"><a href="'.$base_url.'"><img src="'.$base_url.'/sites/members.meta.org.au/themes/openhub/IIN_logo_final.png" /></a></div><div class="iin-nav"><ul class="nav"><li><a href="'.$base_url.'/about-iin">ABOUT</a><ul class="about"><li><a href="'.$base_url.'/australian-innovation-system">The Innovation System</a></li><li><a href="'.$base_url.'/about-precincts">The Precincts</a></li><li><a href="'.$base_url.'/about-network">The Network</a></li></ul></li><li><a href="'.$base_url.'/join-the-conversation">JOIN THE CONVERSATION</a></li><li><a href="'.$base_url.'/innovation-capabilities">INNOVATION CAPABILITIES</a></li><li><a href="'.$base_url.'/community">CONNECT WITH THE COMMUNITY</a></li></ul></div>';
 $block['content'] = '<div id="met-logo"><a href="'.$base_url.'"><img src="'.$base_url.'/sites/all/themes/custom_theme/images/meta-logo.png"></a></div><div class="iin-nav"><ul class="nav"><li><a href="'.$base_url.'/about-this-site">ABOUT THIS SITE</a></li><li><a href="'.$base_url.'/conversations">JOIN THE CONVERSATION</a></li><li><a href="'.$base_url.'/community">THE COMMUNITY</a></li><li><a href="'.$base_url.'/members">MEMBER ORGANISATIONS</a></li><li><a href="'.$base_url.'/partners-providers">PARTNERS AND PROVIDERS</a></li><li><a href="'.$base_url.'/services">SERVICES</a></li><li><a href="'.$base_url.'/uploaded-files">LIBRARY</a></li></ul></div>';

    break;
  }
  return $block;
}
