<?php

/**
  @alexarpen
*/


function collabco_admin_form_node_admin_content_alter(&$form, &$form_state, $form_id) {

  $keys = array(
    'flag_hide_content'
    , 'unflag_hide_content'
    , 'flag_follow'
    , 'unflag_follow'
  );


  _collabco_admin_helper_reorder_keys($form['admin']['options']['operation']['#options'], $keys);
}


function _collabco_admin_helper_reorder_keys(&$arr, $keys) {
  $values = array();
  foreach ($arr as $_key => $_value) {
    if (in_array($_key, $keys)) {
      $values[$_key] = $arr[$_key];
      unset($arr[$_key]);
    }
  }
  foreach ($values as $_key => $_value) {
    $arr[$_key] = $_value;
  }
}

