<?php


function meta_debug_boot() {
  alexar_debug(true);
}

function alexar_debug($debug=true) {
  ini_set('display_errors', $debug);
  ini_set('display_startup_errors', $debug);
  error_reporting(E_ALL);
}

function x($var, $die=true) {
  echo '<xmp>';
  print_r($var);
  echo '</xmp>';
  empty($die) or die(); 
}


function meta_debug_menu() {
	$items = array();
	$items['test23'] = array(
	    'title' => 'Testing function',
	    'description' => 'Testing function desc',
	    'page callback' => '_meta_test',
            'access callback' => TRUE
	);
        return $items;
}

function _meta_test()
{
  //  x("hello");
    meta_email_send_send_for_revision(271,202);
}