<?php

/**
 * Checks if a user is following a node
 * @return
 *   TRUE or FALSE 
 */
function collabco_follow_user_is_following($nid, $account=null) {
	if (isset($account)) {
		$uid = $account->uid;
	} else {
		global $user;
		$uid = $user->uid;
	}
	return (bool) flag_get_user_flags('node', $nid, $uid);
}


/**
 * Lists the follower users of a specific node
 * 
 */
function collabco_follow_get_followers($nid, $flag_name=null) {
	if (!isset($flag_name)) {
		$flag_name = variable_get('collabco_follow_flag_type', 'follow');
	}
       
	//$flags = flag_get_user_flags('node', $nid);
        $flags = flag_get_entity_flags('node', $nid,$flag_name);             
	$users = array();
	foreach ($flags as $flag) {
               
		if (empty($flag->uid)) {
			continue;
		} 
		$users[] = user_load($flag->uid);           
	}
	return $users;
}


