<?php
/**
 * @file
 * Installation functions for the Collabco Mentions module.
 */

/**
 * Implements hook_install().
 */
function collabco_mentions_install() {
  // Enable the Mentions fitler on the 'email' text format.
  db_insert('filter')
    ->fields(array(
      'format' => 'email',
      'module' => 'mentions',
      'name' => 'filter_mentions',
      'status' => 1,
      'settings' => serialize(array()),
    ))
    ->execute();
}
