<?php

/**
 * @file
 * Enable access control for Published and In Draft groups.
 */

/**
 * The access realm of group member.
 */
define('META_OG_STATE_REALM', 'meta_og_state');

/**
 * Group state field, i.e. "Draft/Published" radios on node edit form.
 */
define('META_OG_STATE_FIELD', 'meta_og_state_state');

/**
 * Draft state of radio button.
 */
define('META_OG_STATE_DRAFT', 0);

/**
 * Published state of radio button.
 */
define('META_OG_STATE_PUBLISHED', 1);


function meta_og_state_init() {
  //node_access_rebuild();
}

/**
 * Implements hook_node_grants().
 */
function meta_og_state_node_grants($account, $op) {
  if ($op != 'view') {
    return;
  }
  $groups = array(
    'node' => array(),
  );
  if (user_access('administer group', $account)) {
    $groups = og_get_all_group();
  }
  else {
    $groups = og_get_entity_groups('user', $account);
  }
  
  $grants = array();
  foreach ($groups as $gids) {
    foreach ($gids as $gid) {
      $node = node_load($gid);
      // if user is the owner of admin user for the group give them the key
      if ($node->uid == $account->uid || og_user_access('node', $gid, 'view draft', $account)) {
        $realm = META_OG_STATE_REALM;
        $grants[$realm][] = $gid;
      }
    }
  }
  return $grants;
}

/**
 * Implements hook_node_access_records().
 */
function meta_og_state_node_access_records($node) {
  if (empty($node->status)) {
    // Node is unpublished, so we don't allow any group member to see it
    return array();
  }
  // Make sure that this is a group.
  $gid = $node->nid;
  if (!og_is_group('node', $gid)) {
    return array();
  }
  $state = _meta_og_state_get_state($node);
  $grants = array();
  if ($state == META_OG_STATE_DRAFT) {
    // Just Draft state for now. We can handle other states here later.
    // We just care about 'view' grant. Other grants are being handled by
    // default permissions.
    $grants[] = array(
      'realm' => META_OG_STATE_REALM,
      'gid' => $gid,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
  }
  return $grants;
}

/**
 * Checking if the node is part of a Published or In Draft group.
 */
function _meta_og_state_get_membership_state($og_membership) {
  return isset($og_membership->original->state) ? $og_membership->original->state : FALSE;
}

/**
 * Checking if the node is part of a Published or In Draft group.
 */
function _meta_og_state_get_state($node) {
  $gid = $node->nid;
  if (!og_is_group('node', $gid)) {
    return FALSE;
  }
  $items = field_get_items('node', $node, META_OG_STATE_FIELD);
  if (isset($items[0])) {
    return $items[0]['value'];
  }
  return NULL;
}

/**
 * 
*/
function meta_og_state_is_draft($gid) {
  $group_wrapper = entity_metadata_wrapper('node', $gid);
  if (isset($group_wrapper->{META_OG_STATE_FIELD})) {
    return $group_wrapper->{META_OG_STATE_FIELD}->value() == META_OG_STATE_DRAFT;
  }
  return null;
}

/**
 * Implement hook_og_permission().
 */
function meta_og_state_og_permission() {
  $items = array();
  $items['view draft'] = array(
    'title' => t('View in Draft state'),
    'description' => t('Allow users to view the group in Draft mode.'),
    'default role' => array(OG_ADMINISTRATOR_ROLE),
    'restrict access' => TRUE,
  );
  return $items;
}

/**
 * Implement hook_og_fields_info().
 */
function meta_og_state_og_fields_info() {
  $allowed_values = array(
    META_OG_STATE_DRAFT => 'Draft',
    META_OG_STATE_PUBLISHED =>  'Published',
  );
  $items[META_OG_STATE_FIELD] = array(
    'type' => array('group'),
    'description' => t('Determine the state of a group.'),
    // Open state can be done only on node entity.
    'entity' => array('node'),
    'field' => array(
      'field_name' => META_OG_STATE_FIELD,
      'no_ui' => TRUE,
      'type' => 'list_boolean',
      'cardinality' => 1,
      'settings' => array('allowed_values' => $allowed_values, 'allowed_values_function' => ''),
    ),
    'instance' => array(
      'label' => t('Group state'),
      'required' => TRUE,
      // Default to draft.
      'default_value' => array(0 => array('value' => META_OG_STATE_DRAFT)),
      'widget_type' => 'options_select',
      'view modes' => array(
        'full' => array(
          'label' => 'above',
          'type' => 'options_onoff',
        ),
        'teaser' => array(
          'label' => 'above',
          'type' => 'options_onoff',
        ),
      ),
    ),
  );
  return $items;
}

/**
 * Implementation of hook_field_access().
 *
 * @param $op
 *   The operation to be performed. Possible values:
 *   - 'edit'
 *   - 'view'
 * @param $field
 *   The field on which the operation is to be performed.
 * @param $entity_type
 *   The type of entity; e.g. 'node' or 'user'.
 * @param $entity
 *   The entity on which the operation is to be performed.
 * @param $account
 *   The account to check.
 *
 * @return
 *   FALSE if the operation is not allowed.
 *   Note when field_access() is invoked, access is granted unless one
 *   implementation of hook_field_access() explicitly returns FALSE.
 *
 * @see field_access()
 */
function meta_og_state_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] != META_OG_STATE_FIELD) {
    // If not the "Draft/Published" radios, then we have nothing to do here.
    return;
  }
  if (user_access('administer group')) {
    return TRUE;
  }
  if ($op == 'view') {
    return;
  }
  if (user_access('bypass node access', $account)) {
    return TRUE;
  }
  if (user_access('administer group', $group)) {
    return TRUE;
  }
  return FALSE;
}

function meta_og_state_form_node_form_alter(&$form, &$form_state) {
  if (!isset($form_state['node']->nid)) {
    // New node, set "Draft/Published" to NOT required.
    $form['meta_og_state_state']['und']['#required'] = FALSE;
  } 
}

/**
 * 
 */
function meta_og_state_field_attach_update($entity_type, $entity) {

  if ($entity_type == 'og_membership') {
    $state_new = $entity->state;
    $state_old = _meta_og_state_get_membership_state($entity);
    if ($state_old != $state_new) {
      drupal_set_message(t('Membership state changed from %old to %new', array(
        '%old' => meta_group_og_state_title($state_old),
        '%new' => meta_group_og_state_title($state_new),
      )));
      //meta_email_send_group_published($group->nid);
    }
  }

  if (!isset($entity->nid)) {
    return;
  }
  $nid = $entity->nid;
  if (!meta_group_is_group($nid)) {
    return;
  }
  $group = $entity;
  
  $state_new = _meta_og_state_get_state($group);
  $state_old = _meta_og_state_get_state($group->original);

  if ($state_old == META_OG_STATE_DRAFT and $state_new == META_OG_STATE_PUBLISHED) {
    meta_email_send_group_published($group->nid);
  }
}




