<?php

/**
 * Implements hook_theme().
 */
function iin_profile_block_theme($existing, $type, $theme, $path) {
  return array(
      'header_user_profile_template' => array(
        'template' => 'header-user-profile-template',
       'variables' => array('complete_data'=> NULL),
     ),
  );
}

/**
 * Implements hook_block_info().
 */
function iin_profile_block_block_info() {
  $blocks = array();
  $blocks['iin_profile_block'] = array(
    'info' => t('IIN Profile Block (for front page)'),
  );
  $blocks['header_user_profile_block'] = array(
    'info' => t('Header User Profile Block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function iin_profile_block_block_view($delta='') {
  $block = array();
  global $user;
          global $base_url;
          if (user_is_logged_in()) {
            if (!property_exists($user, 'realname')) {
              $user = user_load($user->uid);
            }
          }
  switch($delta) {
    case 'iin_profile_block' :
      $entity_type = 'node';
      $field = 'title';
      $groups_output = '';
      $groups = og_get_groups_by_user($user);
      if (!empty($groups)) {
        foreach ($groups['node'] as $key => $gid) {
          $node = node_load($gid);
          $group_links = '<a href="'.$base_url.'/node/' . $node->nid . '">' . $node->title . '</a>';
        }
        // DISABLED BY MATT FOR META DEMO. I only disabled the output obviously. Re-enable by removing comment-out.
        /*$groups_output = '<div><h6>Your Groups:</h6><div>' . $group_links . '</div></div>';*/
      }
      
      $links = array(
          'ui-navigation-menu ui-activity-feed  first leaf' => array(
              'title' => '<i class="icon-rss" style="text-decoration:none !important;">&nbsp;</i> Activity Feed'
              , 'href' => sprintf('<front>')             
    		
            , 'html' => TRUE
          )
         , 'ui-navigation-menu ui-my-profile leaf' => array(
              'title' => '<i class="icon-user">&nbsp;</i> My Profile'
              , 'href' => sprintf('user')  	    
            , 'html' => TRUE
          )
        
          , 'ui-navigation-menu ui-your-topics leaf' => array(
              'title' => '<i class="icon-list">&nbsp;</i> My Topics'
              , 'href' => sprintf('your-topics')
          
            , 'html' => TRUE
          )
          , 'ui-navigation-menu ui-your-hubs leaf' => array(
              'title' => '<i class="icon-globe">&nbsp;</i> My Hubs'
              , 'href' => sprintf('profile/hubs')
              , 'html' => TRUE
          )                  
        );
        $attributes = array('class' => array('menu nav user-navigation'));
  
        $navigation_links= theme('links', array(
          'links' => $links, 'attributes' => $attributes
        ));
      
      
      $block['content'] = '<div id="iin-profile-content" class="row-fluid"><div id="iin-profile-picture" >'.theme('user_picture', array('account' => $user)).'</div>
<div>'.$user->realname.'</div></div><br>'. $navigation_links; 
      break;
     case 'header_user_profile_block' :

            $data = array();
            $data['user_name'] = $user->realname;
            //print($data['user_name']);

          //  print($picture);
            $content = theme('header_user_profile_template',$data);
            $block['content'] = $content;
       break;


  }
  return $block;
}

 /**
 * Get all users of a group
 */
function iin_profile_block_get_user_groups($uid) {
  $query = db_select('node', 'n')
    ->fields('n', array('nid'));
    //->join('og_membership', 'm', 'n.nid = m.gid')
    //->condition('m.etid', $uid, '=')
    //->condition('m.type', 'user', '=');
  return $query->execute();
}
