<?php
 
/**
 * Implements hook_theme().
 */
function iin_profile_block_theme($existing, $type, $theme, $path) {
  return array(
      'header_user_profile_template' => array(
        'template' => 'header-user-profile-template',
       'variables' => array('complete_data'=> NULL),
     ),
  );
}
 
/**
 * Implements hook_block_info().
 */
function iin_profile_block_block_info() {
  $blocks = array();
  $blocks['iin_profile_block'] = array(
    'info' => t('IIN Profile Block (for front page)'),
  );
  $blocks['header_user_profile_block'] = array(
    'info' => t('Header User Profile Block'),
  );
  return $blocks;
}
 
/**
 * Implements hook_block_view().
 */
function iin_profile_block_block_view($delta='') {
  $block = array();
  global $user;
          global $base_url;
          if (user_is_logged_in()) {
            if (!property_exists($user, 'realname')) {
              $user = user_load($user->uid);
            }
          }
  switch($delta) {
    case 'iin_profile_block' :
      $entity_type = 'node';
      $field = 'title';
      $groups_output = '';
      $groups = og_get_groups_by_user($user);
      if (!empty($groups)) {
        foreach ($groups['node'] as $key => $gid) {
          $node = node_load($gid);
          $group_links = '<a href="'.$base_url.'/node/' . $node->nid . '">' . $node->title . '</a>';
        }
        // DISABLED BY MATT FOR META DEMO. I only disabled the output obviously. Re-enable by removing comment-out.
        /*$groups_output = '<div><h6>Your Groups:</h6><div>' . $group_links . '</div></div>';*/
      }
      $block['content'] = '<div id="iin-profile-content" class="row-fluid"><div id="iin-profile-picture" >'.theme('user_picture', array('account' => $user)).'</div>
<div>'.$user->realname.'</div></div>';
 /** <div><a href="'.$base_url.'/user">Profile</a> | <a href="'.$base_url.'/user/logout">Logout</a></div></div>' . $groups_output . '<div class="profile-links"><a href="/">Recommended</a></div><div class="profile-links"><a href="/following">Following</a></div>'; */
      break;
     case 'header_user_profile_block' :
 
            $data = array();
            $data['user_name'] = $user->realname;
            //print($data['user_name']);
 
          //  print($picture);
            $content = theme('header_user_profile_template',$data);
            $block['content'] = $content;
       break;
 
 
  }
  return $block;
}
 
 /**
 * Get all users of a group
 */
function iin_profile_block_get_user_groups($uid) {
  $query = db_select('node', 'n')
    ->fields('n', array('nid'));
    //->join('og_membership', 'm', 'n.nid = m.gid')
    //->condition('m.etid', $uid, '=')
    //->condition('m.type', 'user', '=');
  return $query->execute();
}
 