<?php



/**
 * Implements hook_views_api().
 */
function meta_structure_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'meta_structure') . '/includes/views',
  );
}

function meta_structure_menu() {
  $items['topics'] = array(
    'page callback' => '_meta_structure_page_topics',
    'access callback' => 'user_is_logged_in',
  );
  $items['hubs'] = array(
    'page callback' => '_meta_structure_page_hubs',
    'access callback' => TRUE,
  );
  return $items;
}

function _meta_structure_page_topics() {
  // Nothing. this page should be there just for the views.
  return '';
}

function _meta_structure_page_hubs() {
  // Nothing. this page should be there just for the views.
  return '';
}



function meta_structure_preprocess_page(&$vars) {
  $vars['mobile']['block_search'] = _meta_structure_block_view('search', 'form');
  $menu_profile = _meta_structure_block_view('menu', 'menu-profile-menu');
  $menu_secondary = _meta_structure_block_view('menu', 'menu-meta-secondary-menu');
  $menu_primary = _meta_structure_block_view('menu', user_is_logged_in() ? 'menu-main-menu---auth' : 'main-menu-menu-anon');
  $vars['mobile']['block_menu'] = $menu_primary . $menu_secondary;
  $vars['mobile']['block_profile'] = $menu_profile;
}


function _meta_structure_block_view($module, $delta) {
  $block = module_invoke($module, 'block_view', $delta);
  return render($block['content']);
}
