<?php

/**
 * Implements hook_theme().
 */
function hub_actions_theme($existing, $type, $theme, $path) {
  return array(
      'hub_send_for_revision_template' => array(
        'template' => 'hub-send-for-revision',
     ),
    'hub_host_a_topic_template' => array(
        'template' => 'hub-host-a-topic',
     ),
    'hub_host_a_resource_template' => array(
        'template' => 'hub-host-a-resource',
     ),
  );
}

/**
 * Implements hook_block_info().
 */
function hub_actions_block_info() {
  $blocks = array();
  $blocks['hub_send_for_revision'] = array(
    'info' => t('Send for revision in Hub page'),
  ); 
  $blocks['hub_host_a_topic'] = array(
    'info' => t('Host a topic in a Hub'),
  );
  $blocks['hub_host_a_resource'] = array(
    'info' => t('Host a resource in a Hub'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hub_actions_block_view($delta='') {

  $block = array();
  global $base_url;
  // @TODO: Make sure if there is a better way. 

  $nid = arg(1);  
  $node = node_load($nid);
  if (!isset($node->nid) or !og_is_group('node', $node)) {
    return;
  }
  $gid = $node->nid;
            //@FIXME  clean access controls
  $is_admin = user_access('administer group') || og_user_access('node', $gid, 'administer group');
  switch($delta) {
       /* case 'hub_send_for_revision':      
         if ($node->type == 'hub' &&  meta_og_state_is_draft($node->nid) & !arg(2)) {                      
            $content = theme('hub_send_for_revision_template');
            $block['content'] = $content;
          }   
        break; */
        case 'hub_host_a_topic':  
          if ($node->type == 'hub' && arg(2)=='topics') {
           if ($is_admin || og_user_access('node', $nid, 'create conversation content')) { 
                 $content = theme('hub_host_a_topic_template');        
                 $block['content'] = $content;
              }
          }   
        break;
        case 'hub_host_a_resource':      
          if ($node->type == 'hub'  && arg(2)=='library') {  
           if ($is_admin || og_user_access('node', $nid, 'create knowledge_object content')) {    
            $content = theme('hub_host_a_resource_template');
            $block['content'] = $content;
           }
          }   
        break;
  }
  return $block;
}


function template_preprocess_hub_send_for_revision_template(&$variables) {     
        $node = node_load(arg(1));  
        $variables['nid'] = $node->nid;  
}
function template_preprocess_hub_host_a_topic_template(&$variables) {     
        $node = node_load(arg(1));  
        $variables['nid'] = $node->nid;  
}
function template_preprocess_hub_host_a_resource_template(&$variables) {     
        $node = node_load(arg(1));  
        $variables['nid'] = $node->nid;  
}


function hub_actions_form_conversation_node_form_alter(&$form, &$form_state) {

  $gid = intval(arg(3));
  if (!empty($gid)) {
    $lang = LANGUAGE_NONE;
    $form['og_group_ref'][$lang]['#default_value'][] = arg(3);    
  }
  $form['og_group_ref']['#access'] = false;
  array_unshift($form['#submit'], 'hub_actions_form_conversation_node_form_submit');
  
}

function hub_actions_form_conversation_node_form_submit($form, &$form_state) {

  $gid = intval(arg(3));
  if (!empty($gid)) {
    $form_state['values']['og_group_ref'][LANGUAGE_NONE][0]['target_id'] = $gid;
  }
}

function hub_actions_form_knowledge_object_node_form_alter(&$form, &$form_state) {
   
    $gid = intval(arg(3));
  if (!empty($gid)) {    
    $lang = LANGUAGE_NONE;
    $form['og_group_ref'][$lang]['#default_value'][] = $gid;    
  }
   $form['og_group_ref']['#access'] = false;
 
   array_unshift($form['#submit'], 'hub_actions_form_knowledge_object_node_form_submit');
}
 

function hub_actions_form_knowledge_object_node_form_submit($form, &$form_state) {
//    x($form_state['values']);
  $gid = intval(arg(3));
  if (!empty($gid)) {
    $form_state['values']['og_group_ref'][LANGUAGE_NONE][0]['target_id'] = $gid;
  }
}

function hub_actions_node_insert($node)
{
    if ($node->type == 'conversation' or $node->type == 'knowledge_object') 
    {
        $group = field_get_items('node', $node, 'og_group_ref');
        
        if (!empty($group)) {
            $section  = $node->type == 'conversation' ? 'topics':'library';
            $group_markup = field_view_value('node', $node, 'og_group_ref', $group[0]);           
            $url = url('node/'.$group[0]['target_id'].'/'.$section);
            $group_link = '<a class=action href='. $url.'>'. $group_markup['#markup'].'</a>';
            drupal_set_message('Go back to Hub '.$group_link);
        }
        
    }      
    
}