<?php

/**
 * Implements hook_field_access().
 */
function meta_field_access_field_access($op, $field, $entity_type, $entity, $account) {

	if ($field['field_name'] == 'field_provisional_organisation') {
		if ($op != 'edit') {
			return true;
		}
		if (empty($account->uid)) { // This is a Regsiter form
			return true;
		}
		if (user_access('administer users')) {
			return true;
		}
		return false;
	}
  return true;
}
