<?php

/**
 * @file
 * Canned view to display a summary of all user profiles.
 */

/**
 * Implements hook_views_default_views().
 *
function pcp_views_default_views() {

  $view = new view();

/*
  $view->name = 'profile_completeness_summary';
  $view->description = '';
  $view->tag = 'PCP';
  $view->base_table = 'profile';
  $view->human_name = 'Profile completeness summary';
  $view->core = 7;
  $view->api_version = '3.0';

 
  $views[$view->name] = $view;
  
  return $views;
}
 *
 */
