<?php



function meta_landing_menu() {
  $items['user/landing'] = array(
    'page callback' => '_meta_landing_page_landing'
    , 'access callback' => true
  );
  return $items;
}


/**
 * Implements hook_theme().
 */
function meta_landing_theme($existing, $type, $theme, $path) {
  return array(
    'collabco_landing'  => array(
      'template' => 'collabco-landing',
    ),
  );
}


function _meta_landing_page_landing() {
  return theme('collabco_landing');
}


